name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  IMAGE: node-demo
  GIT_HASH: $(git rev-parse --short "$GITHUB_SHA")
  GIT_BRANCH: ${GITHUB_REF#refs/heads/}
  #GIT_N:  git rev-list --count HEAD # warning, resests after 65
  
jobs:
  build:
    runs-on: ubuntu-latest
    #
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $IMAGE:$(date +%s) --tag $IMAGE:${{ github.sha }}
